services:

  postgres:
    image: postgres:16
    container_name: tpo_postgres
    restart: always

    environment:
        POSTGRES_USER: tpo_user
        POSTGRES_PASSWORD: tpo_password
        POSTGRES_DB: tinder_app

    ports:
        - "5433:5432"

    volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: